
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ApprovalRequestScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  requester_address: 'requester_address',
  status: 'status',
  created_at: 'created_at',
  resolved_at: 'resolved_at',
  resolver_address: 'resolver_address'
};

exports.Prisma.AuthNonceScalarFieldEnum = {
  id: 'id',
  walletAddress: 'walletAddress',
  nonce: 'nonce',
  expiresAt: 'expiresAt',
  consumedAt: 'consumedAt',
  createdAt: 'createdAt'
};

exports.Prisma.DelegatedSignatureScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  action: 'action',
  roomId: 'roomId',
  txDigest: 'txDigest',
  signature: 'signature',
  createdAt: 'createdAt'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  rotationCounter: 'rotationCounter',
  createdAt: 'createdAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  walletId: 'walletId',
  jwtId: 'jwtId',
  status: 'status',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt',
  lastUsedAt: 'lastUsedAt',
  encryptedPrivateKey: 'encryptedPrivateKey'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  primaryWalletAddress: 'primaryWalletAddress',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WalletScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  address: 'address',
  type: 'type',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Diesel_schema_migrationsScalarFieldEnum = {
  version: 'version',
  run_on: 'run_on'
};

exports.Prisma.Meeting_roomsScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  title: 'title',
  hosts: 'hosts',
  seal_policy_id: 'seal_policy_id',
  status: 'status',
  max_participants: 'max_participants',
  require_approval: 'require_approval',
  participant_count: 'participant_count',
  created_at: 'created_at',
  started_at: 'started_at',
  ended_at: 'ended_at',
  checkpoint_sequence_number: 'checkpoint_sequence_number',
  transaction_digest: 'transaction_digest',
  indexed_at: 'indexed_at',
  updated_at: 'updated_at'
};

exports.Prisma.Room_metadataScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  dynamic_field_id: 'dynamic_field_id',
  df_version: 'df_version',
  language: 'language',
  timezone: 'timezone',
  recording_blob_id: 'recording_blob_id',
  indexed_at: 'indexed_at',
  updated_at: 'updated_at'
};

exports.Prisma.Room_participantsScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  participant_address: 'participant_address',
  role: 'role',
  admin_cap_id: 'admin_cap_id',
  joined_at: 'joined_at',
  updated_at: 'updated_at'
};

exports.Prisma.WatermarksScalarFieldEnum = {
  pipeline: 'pipeline',
  epoch_hi_inclusive: 'epoch_hi_inclusive',
  checkpoint_hi_inclusive: 'checkpoint_hi_inclusive',
  tx_hi: 'tx_hi',
  timestamp_ms_hi_inclusive: 'timestamp_ms_hi_inclusive',
  reader_lo: 'reader_lo',
  pruner_timestamp: 'pruner_timestamp',
  pruner_hi: 'pruner_hi'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  ApprovalRequest: 'ApprovalRequest',
  AuthNonce: 'AuthNonce',
  DelegatedSignature: 'DelegatedSignature',
  RefreshToken: 'RefreshToken',
  Session: 'Session',
  User: 'User',
  Wallet: 'Wallet',
  diesel_schema_migrations: 'diesel_schema_migrations',
  meeting_rooms: 'meeting_rooms',
  room_metadata: 'room_metadata',
  room_participants: 'room_participants',
  watermarks: 'watermarks'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
